### ISSUE TITLE
Cancellation token in exception handlers

### ISSUE THREAD

**Issue by IharBury** [liquidprojections/LiquidProjections#102]
We would like to use delays in our [exception handlers](https://github.com/liquidprojections/LiquidProjections/blob/320afe8b616991af18ad772e0420f473f566c872/Src/LiquidProjections/Dispatcher.cs#L125). However currently there is no easy way to abort those delays when the subscription is terminated. Adding a `CancellationToken` to the delegate would fix this issue.

**Comment by IharBury** [comment]
The same issue exists for the [`ShouldRetry`](https://github.com/liquidprojections/LiquidProjections/blob/master/Src/LiquidProjections/ShouldRetry.cs) delegate in the projector.

**Comment by dennisdoomen** [comment]
Good point. Would be a breaking chance unfortunately.

**Comment by IharBury** [comment]
> Would be a breaking chance unfortunately.

We could just add new delegates and keep the old ones.

**Comment by IharBury** [comment]
Discussed with @dennisdoomen. We will extend `SubscriptionInfo` with the cancellation token. That will fix the issue with `HandleException` delegate. We will the issue in projector specific delegates later (or maybe we will not fix it at all there) because the `Dispatcher` level exception handling should be enough for most use cases.

**Comment by dennisdoomen** [comment]
So this is now resolved?

**Comment by IharBury** [comment]
Unless we want to provide the cancellation token for projector specific error handlers, we can close all the three issues.

**Comment by dennisdoomen** [comment]
Don't see any priority in this now.
