### ISSUE TITLE
Improve fluent API for more flexibility

### ISSUE THREAD

**Issue by dennisdoomen** [liquidprojections/LiquidProjections#108]
Now | Next
-- | --
Map<Event>().As().When() | Map<Event>().As()
Map<Event>().AsCreateOf().Using() | Map<Event>().AsCreateOf().Using().ThrowingOnDuplicates()
Map<Event>().AsCreateIfDoesNotExistsOf().Using() | Map<Event>().AsCreateOf().Using().IgnoringDuplicates()   
|| Map<Event>().AsUpdateOf().Using().CreatingIfMissing()
  | Map<Event>().AsCreateOf().Using().HandlingDuplicatesUsing(x   => x.)
Map<Event>().AsCreateOrUpdateOf().Using() | Map<Event>().AsCreateOf().Using().OverwritingDuplicates()
Map<Event>().AsUpdateOf().Using() | Map<Event>().AsUpdateOf().Using().ThrowingIfMissing()
Map<Event>().AsUpdateIfExists().Using() | Map<Event>().AsUpdateOf().Using().IgnoringMisses()
  | Map<Event>().AsUpdateOf().Using().HandlingMissesUsing(x   => x)
Map<Event>().AsDeleteOf().Using() | Map<Event>().AsDeleteOf().Using().ThrowingIfMissing()
Map<Event>().AsDeleteIfExists().Using() | Map<Event>().AsDeleteOf().Using().IgnoringMisses()
  | Map<Event>().AsDeleteOf().Using().HandlingMissesUsing(x   => x)

**Comment by dennisdoomen** [comment]
@tomachristian @IharBury

**Comment by IharBury** [comment]
`Map().AsCreateIfDoesNotExistsOf().Using()` can be potentially expressed not only as `Map().AsCreateOf().Using().IgnoringDuplicates()` but also as something like `Map().AsUpdateOf().Using().CreatingIfMissing()`. Do we want to support both or just force using the first one?

**Comment by IharBury** [comment]
I expect `HandlingDuplicatesUsing(x => x.)` to have the following supported paratemeters:

- The event
- The existing projection
- The context (optional)

**Comment by dennisdoomen** [comment]
> Do we want to support both or just force using the first one?

Maybe yes. It would allow consumers to emphasis the create or the update part.
