### ISSUE TITLE
Setup a landing page with docs

### ISSUE THREAD

**Issue by dennisdoomen** [liquidprojections/LiquidProjections#117]
* [x] Logo
* [x] Copy Jekyll site from www.fluentassertions.com -> https://github.com/liquidprojections/LiquidProjections.docs
* [x] SSL certificate
* [x] Analytics ID
* [x] AddSense ID
* [x] DNS name -> liquidprojections.net
* [x] Add docs based on blog posts
* [x] Splash page items
    * [x] "Designed as a library, not a framework" https://www.flaticon.com/free-icon/brick_182640
    * [x] "Battle tested" https://www.flaticon.com/free-icon/tank_182418
    * [x] "Support for NEventStore, NHibernate and RavenDB"  https://www.flaticon.com/free-icon/servers_182395#term=storage&page=1&position=1
    * [x] "Captures years of experience"  https://www.flaticon.com/free-icon/professor_182332#term=professor&page=1&position=1
    * [x] "Designed for extensibility" https://www.flaticon.com/free-icon/puzzle_182584
    * [x] "Embraces Autonomous Projectors" https://www.flaticon.com/free-icon/renewable-energy_182313

**Comment by dennisdoomen** [comment]
@iusername any change I can get you to create another logo?

**Comment by IUsername** [comment]
@dennisdoomen sounds like fun. It will probably be a few days before I can start putting some ideas together but I am on board.

**Comment by dennisdoomen** [comment]
No worries. It'll take a couple of weeks before I'll have a landing page. 

For your information, this article explains what this library is supposed to do. 
https://www.continuousimprover.com/2018/05/building-projections-in-dotnet.html

**Comment by IUsername** [comment]
<img width="895" alt="asset 2 2x" src="https://user-images.githubusercontent.com/2133735/43039916-8d106cee-8cf4-11e8-81e0-f0292c845844.png">

Playing on the idea of the library as a lens (one side of a pair of spectacles) over the stream of events (the pupil / drop).

**Comment by dennisdoomen** [comment]
I love it already!

**Comment by dennisdoomen** [comment]
Maybe a different color like green or orange will make it a bit more distinct from the Fluent Assertions logo

**Comment by IUsername** [comment]
<img width="737" alt="grasset 5 2x" src="https://user-images.githubusercontent.com/2133735/43359995-e66f9884-926a-11e8-88b0-2819ab707728.png">

Green with a few other small tweaks.

**Comment by dennisdoomen** [comment]
Hmm, that green feels a bit like poison. What about #F48024?

**Comment by IUsername** [comment]
<img width="737" alt="mxasset 6 2x" src="https://user-images.githubusercontent.com/2133735/43416712-4b0b0382-93f6-11e8-84ab-ab5a119fe829.png">
I agree - it feels radioactive or like a drop of anti-freeze. #F48024 is on top and I've included a few toned-down options I think work too.

**Comment by dennisdoomen** [comment]
Oeh, I definitely love the orange one. The others are nice two, but the contrast with black is not strong enough. What do you think/

**Comment by IUsername** [comment]
Orange it is. I will get you some final assets in the next few days.

**Comment by dennisdoomen** [comment]
Awesome. Thanks for all the hard work. I'm trying to think of a way to give you more credits, but other than mentioning you on the landing page, I can't think of anything. Can you?

**Comment by dennisdoomen** [comment]
I have a preliminary site running on http://www.liquidprojections.net. 

Where should I link your name to? The FluentAssertions landing page points to your Github profile, but that one is pretty empty.

**Comment by dennisdoomen** [comment]
@IUsername check the final result at https://www.liquidprojections.net 

Oh man, now I should really ask you to create a new logo for https://www.continuousimprover.com/. It looks so old-fashioned now... What would you like to have for that?

**Comment by dennisdoomen** [comment]
> Linking to my Github profile is probably the best option for now

I had a hard time finding your Twitter profile though. 

> that need similar design work and connecting them with me would be great

I can do a shout-out on Twitter. But people need a way to find and contact you. That's not possible with a Github profile.

> I think I can carve out time to put something together

That would be awesome

> I did notice that the site favicon is pulling the icon for Fluent Assertions.

Thanks. I'll fix that. 

> Another option would be to be available for providing guidance on some future architectural challenge. 

Absolutely. You can email me directly, but maybe joining the FluentAssertion Slack channel is more convenient.
