### ISSUE TITLE
Unit tests/specs do not run

### ISSUE THREAD

**Issue by Corniel** [liquidprojections/LiquidProjections#122]
When retrieving the repository locally, I could build the solution with Visual Studio 2019, and the unit tests (from the `LiquidProjections.Specs` project) where recognized a such (70 in total), however, Visual Studio refuses the run them.

I tried to convert the (VS2017 style project) to a .NET Core 3.1 xUnit test project, without any success. Also, in both cases, the command `dotnet test` told me that no unit tests could be resolved.

Am I doing something wrong here?

**Comment by dennisdoomen** [comment]
It's not you. I've been using Visual Studio 2017 and ReSharper for years, and since two years, only Rider. They come with XUnit support built-in. You'll need to add the `xunit.runner.visualstudio` Nuget package to the `.specs` project to have VS recognize XUnit tests.

**Comment by Corniel** [comment]
See #123 .
