### ISSUE TITLE
Support for netcore

### ISSUE THREAD

**Issue by DejanMilicic** [liquidprojections/LiquidProjections#76]
I would like to use https://www.nuget.org/packages/LiquidProjections.RavenDB/ with netcore1.0 ASP.NET project.  As far as I can see LiquidProjections.RavenDB nor LiquidProjections have any dependencies that would prevent this?

**Comment by dennisdoomen** [comment]
No, but AFAIK RavenDB doesn't run on .NET Core.

**Comment by DejanMilicic** [comment]
When you work with RavenDB from netcore project, all you need is client
https://www.nuget.org/packages/RavenDB.Client/3.5.3-patch-35187
which supports NetStandard.

That is how I use it at the moment

**Comment by DejanMilicic** [comment]
So, it would come down just to changing nuspec for appropriate target platforms

**Comment by dennisdoomen** [comment]
No, need to change the target as well.

**Comment by dennisdoomen** [comment]
OK. I've done some experimenting yesterday and concluded that I need to cross-compile the project to both .NET 4.5 as well as NET Standard 1.3 to make this work.

**Comment by DejanMilicic** [comment]
@dennisdoomen I hope you will have time for this in a near future

**Comment by galenp** [comment]
+1
